
const stats = [
  {
    value: "8.9x",
    description:
      "Our clients grow 8.9 times faster than the average agency (based on client feedback.)",
  },
  {
    value: "90days",
    description: "Typical timeframe to see significant, measurable results",
  },
  {
    value: "$1B+",
    description: "Generated by our clients using our Growth System",
  },
];

const StatsSection = () => {
  return (
    <div className="w-full bg-[#132528] py-20 px-4">
      <div className="max-w-[1440px] mx-auto">
        <h2 className="text-center text-3xl md:text-[40px] font-bold mb-14 md:mb-[120px] text-[#F8FCEC] uppercase ">
          AN OPERATING SYSTEM WORTH BELIEVING IN
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10 md:gap-5">
          {stats.map((stat, index) => (
            <div
              key={index}
              className={`
                ${
                  index !== stats.length - 1
                    ? "border-b border-gray-700 md:border-b-0 md:border-r md:border-gray-700"
                    : ""
                }
                flex flex-col
                px-4 md:px-0 pb-6 md:pb-0
              `}
            >
              <h3 className="text-5xl md:text-[104px] font-medium text-[#BECEB7] mb-4 text-center">
                {stat.value}
              </h3>
              <p className="text-[#E2E8F0] text-base md:text-[21px] max-w-[440px]">
                {stat.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default StatsSection;
